import "@mdxeditor/editor/style.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppProvider } from "./context-providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <AppProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} mx-auto max-w-[84rem]`}>
          <div className="flex flex-col gap-10 px-8">
            <header className="mt-6">
              <nav className="flex gap-4">
                <a href="/" className="font-black text-3xl">
                  Logo
                </a>
              </nav>
            </header>
            <main>{children}</main>
            <footer></footer>
          </div>
        </body>
      </html>
    </AppProvider>
  );
}
